### ISSUE TITLE
When will Send Consumption Information be supported?

### ISSUE THREAD

**Issue by ieliwb** [readdle/app-store-server-api#1]
Thanks.

**Comment by pkotets** [comment]
Hello,

I'm working on missing endpoints and already have a branch with all of them implemented.
Testing is going to take some time, so I guess it will be released in ~1 week.

**Comment by ieliwb** [comment]
Thanks !

**Comment by ieliwb** [comment]
@pkotets Hello, when will support be available? Thanks～

**Comment by pkotets** [comment]
> @pkotets Hello, when will support be available? Thanks～

Today :)

Please, update the library, try out new endpoint(s), and leave your feedback.

**Comment by ieliwb** [comment]
Thanks ~
