### ISSUE TITLE
Backend Transaction Validation Similar to verifyReceipt API

### ISSUE THREAD

**Issue by ArtemRedchych** [readdle/app-store-server-api#10]
Hi,

I was wondering if your system supports backend transaction validation similar to what was possible with the verifyReceipt API. If yes, could you provide some details or documentation on how to implement this?

Thanks

**Comment by pkotets** [comment]
Hi,

Speaking of receipt verification, this is not a responsibility of this library (as it provides only features available through the App Store Server API).

However, I have another library which does exactly what you are looking for: https://github.com/readdle/app-store-receipt-verification.

Let me know if this answer addresses your question :)

**Comment by ArtemRedchych** [comment]
Thank you very much, it's exactly what I needed
