### ISSUE TITLE
Unable to get data from HTTPRequestFailed Exception

### ISSUE THREAD

**Issue by soxft** [readdle/app-store-server-api#14]
Unable to get data from HTTPRequestFailed Exception,

when i use `$api->getTransactionInfo($transactionID)`, when  `$transactionID` is not exists, this request should be 404,

and a `HTTPRequestFailed ` will throw, but we could not get any responseText or statusCode from `HTTPRequestFailed`, so i cant 'let my program' to handle such errors

**Comment by pkotets** [comment]
Hi there,

Thanks for pointing this out to me!

I've implemented it in a bit different way in v3.7.0, so closing this issue.
Feel free to reopen if you need any additional functionality related to this topic.
