### ISSUE TITLE
failed with status code 401. Response text is: Unauthenticated

### ISSUE THREAD

**Issue by 313654021** [readdle/app-store-server-api#19]
in sandbox environment, payload ttl default value is 1 hour,it will get 401 error code.
when i change the ttl to 5 minute,it work fine. maybe this is also the reason for the #18 issue 
so i think client instance need ttl param to change the default value.
sorry for my poor english.

**Comment by yosun** [comment]
same issue

**Comment by pkotets** [comment]
Hey guys,

Thanks for the report.
Never had this kind on an issue, but I assume that it is totally realistic scenario, so v3.8.1 has just been released to address it.

Hope this will fix the issue.

**Comment by 313654021** [comment]
It works thanks
