### ISSUE TITLE
Syntax error in pagination

### ISSUE THREAD

**Issue by JamieSTV** [readdle/app-store-server-api#2]
when calling getTransactionHistory or getNotificationHistory we receive the error

`// ParseError: syntax error, unexpected '(' in file /var/www/app/vendor/readdle/app-store-server-api/src/Response/PageableResponse.php on line 65`

The line in the file is:
```
$nextRequest = new (get_class($page->originalRequest))(...
```

request that this could please be updated to:
```
$class = get_class($queryParams);
$nextRequest = new $class(
```

which seems to fix the issue. 

I've submitted a PR for your approval here: https://github.com/readdle/app-store-server-api/pull/3

**Comment by pkotets** [comment]
Hello,

Indeed, PHP 7.4 doesn't support this way of instantiation. I'm working in PHP 8+ environment and rely on PHPStorm on notifying me about all these incompatibilities, but this time it failed :)

Thanks for the fix, I've merged it.

**Comment by pkotets** [comment]
PR merged, closing issue.
