### ISSUE TITLE
Add refundPreference and consumptionRequestReason fields

### ISSUE THREAD

**Issue by sedlak477** [readdle/app-store-server-api#22]
Hey,
I am currently working on a project using your library and it's been very useful so far.

I've noticed however that some fields are missing in the `ConsumptionRequestBody` and the `AppMetadata` classes. Specifically in the `ConsumptionRequestBody` the `int refundPreference` (see: https://developer.apple.com/documentation/appstoreserverapi/refundpreference) and in `AppMetadata` the `string consumptionRequestReason` (see: https://developer.apple.com/documentation/appstoreservernotifications/consumptionrequestreason) are missing.

I'd love for them to be added to the library so I can continue using it for my project. I would be willing to submit a Pull Request with the changes I need if I get some guidance. In my understanding for the `ConsumptionRequestBody` I just need to add a `protected int` field in the class and add constants for the options. For the `consumptionRequestReason` in `AppMetadata` I'd add a `private ?string` field, add a public getter function, and add `consumptionRequestReason` to the `$typeCaster` in the `createFromRawData(...)` function.

Let me know if these changes are ok and if you'd like me to submit a Pull Request or not.

Thanks for providing this great library! 😀

**Comment by pkotets** [comment]
Hi there,

Thanks for your interest to the library. Happy that it come in handy :)

Regarding changes you mentioned, these field were added later, I haven't had a chance to add them yet. The description of changes, you're proposing is correct, except the fact that the field `refundPreference` of `Consumption Request` object is not required (the only one, so far). So it would be necessary to change the value of `requiredFields` of this object from `*` to the list of all required fields (all of them, except `refundPreference`).

No worries, you can submit your PR as you see it, I will take a look anyway and add what's missing.

**Comment by pkotets** [comment]
New version 3.10.0 has just been released
