### ISSUE TITLE
Property accessed before initialization

### ISSUE THREAD

**Issue by javiermarinros** [readdle/app-store-server-api#26]
I am getting this error when using `sendConsumptionInformation` in v3.10.1:

> Error: Typed property Readdle\AppStoreServerAPI\RequestBody\ConsumptionRequestBody::$refundPreference must not be accessed before initialization

Located at `vendor/readdle/app-store-server-api/src/Request/AbstractRequestParamsBag.php:173`

I hope this info helps.

Thank you!

**Comment by pkotets** [comment]
Hi,

Thanks a lot for this report. Indeed, the bug was introduced while new parameter was being added to this request.

I've just released v3.10.2 which addresses this issue, let me know if it works for you.

**Comment by javiermarinros** [comment]
That was quick! Thank you!
I will let you know if the issue arises again.

**Comment by pkotets** [comment]
Closing the issue for now. Feel free to reopen if anything else is needed.
